version: "3.8"

networks:
  external_payment:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: external_payment-nginx
    ports:
      - "5555:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - external_payment
  mysql:
    image: mysql:5.7
    container_name: external_payment-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./storage/app/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'external_payment'
      MYSQL_USER: 'external_payment'
      MYSQL_PASSWORD: 'external_payment'
      MYSQL_ROOT_PASSWORD: 'external_payment'
    networks:
      - external_payment
  php:
    build:
      args:
        main_user: 'external_payment'
        user: 'external_payment'
        uid: ${DOCKER_UID}
      context: ./docker/php
      dockerfile: ./Dockerfile
    container_name: external_payment-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - external_payment
